### ISSUE TITLE
BatchJacobian_AD.pye is corrupted

### ISSUE THREAD

**Issue by jpcurbelo** [mhpi/HydroDLAdj#1]
Hi @Yalan-Song, thanks for sharing this. I'm trying to run your code to reproduce your paper results but the file _BatchJacobian_AD.pye_ appears to be corrupted. Any solution in mind? Thanks.

**Comment by Yalan-Song** [comment]
Thanks for letting us know. This issue has been fixed by uploading a new batchJacobian.pye file. Please re-download our code, and you may also need to upgrade your PyTorch. A new environment file has been uploaded as well

**Comment by jpcurbelo** [comment]
Hi! Thanks for sharing the updated file. I downloaded the data using `gdown` instructions and was able to run the code. I'll set this as resolved.
